name: CMIP6_Python
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.7.4.post0=py39h2bbff1b_2
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asciitree=0.3.3=py_2
  - async-timeout=3.0.1=py39haa95532_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py39haa95532_0
  - bokeh=2.3.3=py39haa95532_0
  - bottleneck=1.3.2=py39h5d4886f_4
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2021.10.8=h5b45459_0
  - cached-property=1.5.2=py_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cartopy=0.18.0=py39h80a4efb_1
  - certifi=2021.10.8=py39hcbf5309_0
  - cffi=1.14.6=py39h2bbff1b_0
  - cftime=1.5.0=py39h080aedc_0
  - chardet=4.0.0=py39haa95532_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.1=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cmip6_preprocessing=0.5.0=pyhd8ed1ab_0
  - cmocean=2.0=py_3
  - colorama=0.4.4=pyhd3eb1b0_0
  - colorspacious=1.1.2=pyh24bf2e0_0
  - cryptography=3.4.8=py39h71e12ea_0
  - curl=7.79.1=h789b8ee_1
  - cycler=0.10.0=py39haa95532_0
  - cytoolz=0.11.0=py39h2bbff1b_0
  - dask=2021.9.1=pyhd8ed1ab_0
  - dask-core=2021.9.1=pyhd8ed1ab_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - distributed=2021.9.1=py39hcbf5309_0
  - entrypoints=0.3=py39haa95532_0
  - fasteners=0.16.3=pyhd3eb1b0_0
  - fastprogress=1.0.0=py_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - fsspec=0.9.0=pyhd8ed1ab_2
  - gcsfs=0.8.0=pyhd8ed1ab_2
  - geos=3.8.0=h33f27b4_0
  - google-api-core=1.31.2=pyhd8ed1ab_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-cloud-core=1.7.2=pyh6c4a22f_0
  - google-cloud-storage=1.30.0=pyh9f0ad1d_0
  - google-crc32c=1.1.2=py39h2bbff1b_0
  - google-resumable-media=1.3.3=pyh6c4a22f_0
  - googleapis-common-protos=1.53.0=py39h35db3c3_0
  - grpcio=1.38.1=py39hb76b349_0
  - h5netcdf=0.11.0=pyhd8ed1ab_0
  - h5py=3.4.0=nompi_py39hd4deaf1_101
  - hdf4=4.2.15=h0e5069d_3
  - hdf5=1.12.1=nompi_h2a0e4a3_101
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icc_rt=2019.0.0=h0cc432a_1
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py39haa95532_0
  - intake=0.6.3=pyhd3eb1b0_0
  - intake-esm=2021.8.17=pyhd8ed1ab_0
  - intel-openmp=2021.3.0=haa95532_3372
  - ipython=7.27.0=py39hd4e2768_0
  - jedi=0.18.0=py39haa95532_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - kiwisolver=1.3.1=py39hd77b12b_0
  - krb5=1.19.2=h5b6d351_0
  - libcrc32c=1.1.1=ha925a31_2
  - libcurl=7.79.1=h789b8ee_1
  - libnetcdf=4.8.1=nompi_h1cc8e9d_101
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.18.1=h7755175_0
  - libssh2=1.10.0=h680486a_2
  - libtiff=4.2.0=hd0e1b90_0
  - libzip=1.8.0=hfed4ece_1
  - libzlib=1.2.11=h8ffe710_1013
  - locket=0.2.1=py39haa95532_1
  - lz4-c=1.9.3=h2bbff1b_1
  - markupsafe=2.0.1=py39h2bbff1b_0
  - matplotlib-base=3.4.2=py39h49ac443_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.0=py39h277e83a_2
  - mkl_random=1.2.2=py39hf11a4ad_0
  - msgpack-python=1.0.2=py39h59b6b97_1
  - multidict=5.1.0=py39h2bbff1b_2
  - munkres=1.1.4=py_0
  - netcdf4=1.5.7=nompi_py39hf113b1f_103
  - numcodecs=0.8.0=py39hd77b12b_0
  - numexpr=2.7.3=py39hb80d3ca_1
  - numpy=1.21.2=py39hfca59bb_0
  - numpy-base=1.21.2=py39h0829f74_0
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1l=h8ffe710_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.3.3=py39h6214cd6_0
  - parso=0.8.2=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py39h4fa10fc_0
  - pip=21.2.4=py39haa95532_0
  - proj=6.2.1=h9f7ef89_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.18.1=py39h415ef7b_0
  - psutil=5.8.0=py39h2bbff1b_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyjwt=2.1.0=py39haa95532_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyshp=2.1.3=pyhd3eb1b0_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.7=h6244533_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-snappy=0.6.0=py39hd77b12b_3
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd3eb1b0_0
  - pyyaml=5.4.1=py39h2bbff1b_1
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.7.1=py39hbe87c03_2
  - setuptools=58.0.4=py39haa95532_0
  - shapely=1.7.1=py39h06580b3_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=h33f27b4_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tk=8.6.11=h2bbff1b_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - tornado=6.1=py39h2bbff1b_0
  - traitlets=5.1.0=pyhd3eb1b0_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021a=h5d7bf9c_0
  - ujson=4.2.0=py39h415ef7b_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
  - xarray=0.19.0=pyhd8ed1ab_1
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - yarl=1.6.3=py39h2bbff1b_0
  - zarr=2.8.1=pyhd3eb1b0_0
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h8ffe710_1013
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - debugpy==1.5.0
    - ipykernel==6.4.1
    - ipython-genutils==0.2.0
    - jupyter-client==7.0.6
    - jupyter-core==4.8.1
    - nest-asyncio==1.5.1
    - pywin32==302
    - pyzmq==22.3.0
prefix: C:\Users\Denisse\AppData\Local\R-MINI~1\envs\CMIP6_Python
